services:
  msr:
    build:
      context: ./build
      args:
        - __ibm_wm_msr_image=${WZP_DEV_CONTAINER_IMAGE}:${WZP_DEV_CONTAINER_TAG}
    image: wz-dev-01
    container_name: 2l-wzdev1
    hostname: 2l-wzdev1
    volumes:
      ## MSR License
      # - ${WZP_HOST_MSR_LICENSE_FILE_LOCATION}:${WZP_GUEST_MOUNT_POINT_LICENSE_FILE}
      ## MSR properties
      - ./config/MSR/application.properties:${WZP_GUEST_MOUNT_POINT_APPLICATION_PROPERTIES}
      # Our Code, converted to Z convention
      - ../../01-code/is-packages/ZxTools/:${WZP_GUEST_PACKAGES_FOLDER}/ZxTools/
      - ../../01-code/is-packages/ZxToolsLocalTest/:${WZP_GUEST_PACKAGES_FOLDER}/ZxToolsLocalTest/
      - ../../01-code/is-packages/ZyAssert/:${WZP_GUEST_PACKAGES_FOLDER}/ZyAssert/
      - ../../01-code/is-packages/ZyAssertLocalTest/:${WZP_GUEST_PACKAGES_FOLDER}/ZyAssertLocalTest/
      - ../../01-code/is-packages/ZzConfig/:${WZP_GUEST_PACKAGES_FOLDER}/ZzConfig/
      - ../../01-code/is-packages/ZzConfigLocalTest/:${WZP_GUEST_PACKAGES_FOLDER}/ZzConfigLocalTest/
      - ../../01-code/is-packages/ZzUtil/:${WZP_GUEST_PACKAGES_FOLDER}/ZzUtil/
      - ../../01-code/is-packages/ZzUtilAdvanced/:${WZP_GUEST_PACKAGES_FOLDER}/ZzUtilAdvanced/
      - ../../01-code/is-packages/ZzUtilAdvancedLocalTest/:${WZP_GUEST_PACKAGES_FOLDER}/ZzUtilAdvancedLocalTest/
      - ../../01-code/is-packages/ZzUtilLocalTest/:${WZP_GUEST_PACKAGES_FOLDER}/ZzUtilLocalTest/
      - ../../01-code/is-packages/ZzWrappers/:${WZP_GUEST_PACKAGES_FOLDER}/ZzWrappers/
      ## Still to convert
      - ../../01-code/is-packages/WxSimpleConfig/:${WZP_GUEST_PACKAGES_FOLDER}/WxSimpleConfig/
      - ../../01-code/is-packages/WxSimpleConfigTest/:${WZP_GUEST_PACKAGES_FOLDER}/WxSimpleConfigTest/
      - ../../01-code/is-packages/WzLog/:${WZP_GUEST_PACKAGES_FOLDER}/WzLog/
      - ../../01-code/is-packages/WzLogManualTest/:${WZP_GUEST_PACKAGES_FOLDER}/WzLogManualTest/
      - ../../01-code/is-packages/WzTDataGen/:${WZP_GUEST_PACKAGES_FOLDER}/WzTDataGen/
      - ../../01-code/is-packages/WzTestManager/:${WZP_GUEST_PACKAGES_FOLDER}/WzTestManager/
      - ../../01-code/is-packages/WzTestManagerManualTest/:${WZP_GUEST_PACKAGES_FOLDER}/WzTestManagerManualTest/
      - ../../01-code/is-packages/WzTMocks/:${WZP_GUEST_PACKAGES_FOLDER}/WzTMocks/
      - ../../01-code/is-packages/WzTMocksLocalTest/:${WZP_GUEST_PACKAGES_FOLDER}/WzTMocksLocalTest/
      - ../../01-code/is-packages/WzTTools/:${WZP_GUEST_PACKAGES_FOLDER}/WzTTools/
      - ../../01-code/is-packages/WzTToolsLocalTest/:${WZP_GUEST_PACKAGES_FOLDER}/WzTToolsLocalTest/
      # Temp
      - ../../01-code/is-packages/WzTemp/:${WZP_GUEST_PACKAGES_FOLDER}/WzTemp/
    environment:
      # TODO: check SAG_ variable names after IBM's acquisition
      # - SAG_IS_LICENSE_FILE=${WZP_GUEST_MOUNT_POINT_LICENSE_FILE}
      - SAG_IS_CONFIG_PROPERTIES=${WZP_GUEST_MOUNT_POINT_APPLICATION_PROPERTIES}
      - IS_ADMIN_PWD
    ports:
      - ${WZP_PORT_PREFIX}55:5555
    depends_on:
      um:
        condition: service_healthy
  um:
    image: ${WZP_DEV_UM_CONTAINER_IMAGE}:${WZP_DEV_UM_CONTAINER_TAG}
    container_name: 2l-wzdev1-um
    hostname: 2l-wzdev1-um
    volumes:
      - um_data:${WZP_GUEST_MOUNT_POINT_UM_REALM_DATA}
      - ./config/UM/Licence/:${WZP_GUEST_MOUNT_POINT_UM_REALM_LICENSE_FOLDER}
      - um_logs:${WZP_GUEST_MOUNT_POINT_UM_REALM_LOGS}
      - um_users:${WZP_GUEST_MOUNT_POINT_UM_REALM_USERS}
    ports:
      - ${WZP_PORT_PREFIX}90:9000
    environment:
      - REALM_NAME=wzdev01

volumes:
  um_data: {}
  um_logs: {}
  um_users: {}