# ----------------------------
# Connection Pool Aliases
# ----------------------------
jdbcfunc.ISInternal.connPoolAlias=DBPool
jdbcfunc.ISCoreAudit.connPoolAlias=DBPool
jdbcfunc.ActiveTransfer.connPoolAlias=DBPool
jdbcfunc.CentralUsers.connPoolAlias=DBPool
jdbcfunc.ActiveTransferArchive.connPoolAlias=DBPoolArchive


# ----------------------------
# Primary Database Pool (DBPool)
# ----------------------------

jdbc.DBPool.dbURL=jdbc\:wm\:postgresql\://db:5432;databaseName=$env{EX04_WM_DB_NAME}
jdbc.DBPool.userid=$env{EX04_WM_DB_USER_NAME}
jdbc.DBPool.password=$env{EX04_WM_DB_USER_PASS}
jdbc.DBPool.driverAlias=DataDirect Connect JDBC PostgreSQL Driver
jdbc.DBPool.minConns=1
jdbc.DBPool.maxConns=10


# ----------------------------
# Archive DB Pool (DBPoolArchive)
# ----------------------------
jdbc.DBPoolArchive.dbURL=jdbc\:wm\:postgresql\://db:5432;databaseName=$env{EX04_WM_ARCHIVE_DB_NAME}
jdbc.DBPoolArchive.userid=$env{EX04_WM_ARCHIVE_DB_USER_NAME}
jdbc.DBPoolArchive.password=$env{EX04_WM_ARCHIVE_DB_USER_PASS}
jdbc.DBPoolArchive.driverAlias=DataDirect Connect JDBC PostgreSQL Driver
jdbc.DBPoolArchive.minConns=1
jdbc.DBPoolArchive.maxConns=10
