## Generic values useful for development
settings.watt.server.ns.hideWmRoot=false
settings.watt.debug.level=Info
settings.watt.um.clientLog.level=Off
settings.watt.server.ns.lockingMode=none
settings.watt.server.saveConfigFiles=false
settings.watt.server.audit.logFilesToKeep=1
settings.watt.server.serverlogFilesToKeep=1
settings.watt.server.stats.logFilesToKeep=1

# ----------------------------
# Connection Pool Aliases
# ----------------------------
jdbcfunc.ISInternal.connPoolAlias=DBPool
jdbcfunc.ISCoreAudit.connPoolAlias=DBPool
jdbcfunc.ActiveTransfer.connPoolAlias=DBPool
jdbcfunc.CentralUsers.connPoolAlias=DBPool
jdbcfunc.ActiveTransferArchive.connPoolAlias=DBPoolArchive


# ----------------------------
# Primary Database Pool (DBPool)
# ----------------------------

jdbc.DBPool.dbURL=jdbc\:wm\:postgresql\://db:5432;databaseName=$env{WZP_WM_DB_NAME}
jdbc.DBPool.userid=$env{WZP_WM_DB_USER_NAME}
jdbc.DBPool.password=$env{WZP_WM_DB_USER_PASS}
jdbc.DBPool.driverAlias=DataDirect Connect JDBC PostgreSQL Driver
jdbc.DBPool.minConns=1
jdbc.DBPool.maxConns=10


# ----------------------------
# Archive DB Pool (DBPoolArchive)
# ----------------------------
jdbc.DBPoolArchive.dbURL=jdbc\:wm\:postgresql\://db:5432;databaseName=$env{WZP_WM_ARCHIVE_DB_NAME}
jdbc.DBPoolArchive.userid=$env{WZP_WM_ARCHIVE_DB_USER_NAME}
jdbc.DBPoolArchive.password=$env{WZP_WM_ARCHIVE_DB_USER_PASS}
jdbc.DBPoolArchive.driverAlias=DataDirect Connect JDBC PostgreSQL Driver
jdbc.DBPoolArchive.minConns=1
jdbc.DBPoolArchive.maxConns=10
