## Generic values useful for development
settings.watt.server.ns.hideWmRoot=false
settings.watt.debug.level=Info
settings.watt.um.clientLog.level=Off
settings.watt.server.ns.lockingMode=none
settings.watt.server.saveConfigFiles=false
settings.watt.server.audit.logFilesToKeep=1
settings.watt.server.serverlogFilesToKeep=1
settings.watt.server.stats.logFilesToKeep=1

# Universal messaging for development
## Part 1 - webMethods messaging
messaging.WZDEV.CLIENTPREFIX=wzdev
messaging.WZDEV.csqDrainInOrder=true
messaging.WZDEV.csqSize=0
messaging.WZDEV.default=false
messaging.WZDEV.description=webMethods Z Utils
messaging.WZDEV.enabled=true
messaging.WZDEV.isClientPrefixShared=true
messaging.WZDEV.type=UM
messaging.WZDEV.um_loggingOutput=0
messaging.WZDEV.um_publishWaitTime=30000
messaging.WZDEV.url=nsp://um:9000
messaging.WZDEV.useCSQ=false
messaging.WZDEV.enableRequestReply=false

## Part 2 - JNDI
jndi.demo.initialContextFactory=com.pcbsys.nirvana.nSpace.NirvanaContextFactory
jndi.demo.providerURL=nsp://um:9000
jms.demo.jndi_jndiAliasName=demo
